// <auto-generated />
namespace Identity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class NewClasses : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewClasses));
        
        string IMigrationMetadata.Id
        {
            get { return "202207071214017_NewClasses"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
